In [1]:
import numpy as np


In [2]:
# extract all odd numbers from array
ar = np.array(np.random.randint(0, 100, 20))
odd_cases = ar[ar%2!=0]
odd_cases

array([79, 53, 93, 73, 61, 49, 11, 65, 17, 47, 79])

In [3]:
# Create a 3×3 numpy array of all True’s
np.ones([3, 3], dtype=bool)
np.full([3,3], True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# Replace all even numbers in arr with 0
arr =  np.array(np.random.randint(0, 100, 10))
case = arr%2==0
arr[case] = 0
arr

# Replace all even numbers in arr with 0 without changing original array
arr =  np.array(np.random.randint(0, 100, 10))
new_arr = np.where(case, 0, arr)
new_arr

array([39,  0,  0,  0,  0,  0,  0,  0,  0, 18])

In [5]:
# Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr = np.vstack([arr, arr])

# method II
arr = np.arange(10)
arr = arr.reshape(2,5) 
# arr.reshape(2, -1) # Setting -1 atomatically detects no. of cols.
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# Q. Stack the arrays a and b horizontally.
# Difficulty Level: L2

arr = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2, -1)
np.hstack([arr, arr2])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [7]:
# Difficulty Level: L2
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a
# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])
vstacked = np.vstack([a, a, a])
hstacked = np.hstack([a, a, a])
arr = np.reshape(vstacked, -1, order="F")
np.concatenate([arr, hstacked])
# Alternative
np.concatenate([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [8]:
# Q. Get the common items between a and b L2
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [9]:
# Q. From array a remove all items present in array b L2
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])